resources:
  - ../../base

patches:
  - target:
      kind: Deployment
      name: blue-green-demo
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: sd171991/iciciproject:v1

